/* Autogenerated by png2wx.pl on Thu May  9 12:13:39 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_locapi_pi;

#endif /* ICONS_H */
